import { Language } from '../types';

export const translations: Record<Language, Record<string, string>> = {
  ar: {
    portalTitle: 'أهلاً بكم في Happy Kids Zone', portalSubtitle: 'عالم السعادة والمأكولات اللذيذة للأطفال والعائلة', customerView: 'واجهة منيو الأطفال والعائلة', customerViewDesc: 'استعرض أشهى الوجبات المرحة، وجبات الأبطال الصغار، السناكس، الحلويات والمشروبات', exploreMenuBtn: 'الدخول إلى المنيو اللذيذ', openInNewTab: 'فتح في صفحة مستقلة', standaloneMenuHint: 'صفحة منفصلة بالكامل بدون أدوات تحكم', directMenuLink: 'رابط المنيو المباشر', copyLinkSuccess: 'تم نسخ رابط المنيو!', viewMenuPage: 'عرض صفحة المنيو', adminView: 'لوحة التحكم والمدير', adminViewDesc: 'إدارة وتعديل الأصناف والوجبات، تعديل الأسعار الفورية، وتخصيص واجهة Hero', enterAdminBtn: 'تسجيل الدخول كمدير', defaultLoginHint: 'بيانات الدخول الافتراضية: اسم المستخدم admin / كلمة المرور admin123',
    loginTitle: 'تسجيل الدخول للوحة الإدارة', usernameLabel: 'اسم المدير (Username)', passwordLabel: 'كلمة المرور (Password)', loginAction: 'دخول للوحة التحكم', loginError: 'اسم المستخدم أو كلمة المرور غير صحيحة', cancel: 'إلغاء',
    backToPortal: 'الرئيسية / تبديل الواجهة', adminBadge: 'لوحة الإدارة', logout: 'تسجيل خروج', searchPlaceholder: 'ابحث عن وجبة، مشاوي، حلى...', special: 'فاخر', availableNow: 'متوفر الآن',
    exploreMenu: 'تصفح قائمة الطعام', manageMenu: 'لوحة الإدارة وتعديل الأسعار', chefSpecial: 'اختيار الشيف',
    menuTitle: 'قائمة الطعام الفاخرة', menuSubtitle: 'مأكولات شهية محضرة يومياً بأيدي أمهر الطهاة', allCategories: 'الكل', sortBy: 'الترتيب', sortSpecialFirst: 'المميز أولاً', sortPopular: 'الأكثر طلباً', sortPriceAsc: 'السعر: من الأقل', sortPriceDesc: 'السعر: من الأعلى', noItemsFound: 'لا توجد أطباق تطابق بحثك حالياً', viewAllDishes: 'عرض جميع الأطباق', searchResultFor: 'نتائج البحث عن:', clearSearch: 'إلغاء البحث',
    layoutMode: 'طريقة العرض', layoutGrid: 'عرض شبكي (بطاقات)', layoutHorizontal: 'عرض أفقي (قائمة عريضة)', layoutCarousel: 'شريط تصفح أفقي', layoutGridShort: 'شبكي', layoutHorizontalShort: 'أفقي (عرضي)', layoutCarouselShort: 'شريطي', prevDish: 'الوجبة السابقة', nextDish: 'الوجبة التالية',
    minutes: 'دقيقة', calories: 'سعرة', popularBadge: 'الأكثر طلباً', specialBadge: 'طبق مميز', notAvailable: 'غير متوفر مؤقتاً', discount: 'خصم', editItem: 'تعديل', deleteItem: 'حذف',
    adminDashboardTitle: 'لوحة تحكم وإدارة المطعم', adminDashboardSubtitle: 'إضافة وتعديل الأصناف والوجبات، تحديث الأسعار، وتخصيص واجهة Hero', tabItems: 'الوجبات والأسعار', tabCategories: 'إدارة الأصناف (Categories)', tabHero: 'تعديل كتابات HERO', tabDrive: 'Google Drive', tabSettings: 'إعدادات المطعم والأمان',
    addNewItem: 'إضافة وجبة جديدة', itemsList: 'قائمة الأطباق وتعديل الأسعار', searchInItems: 'ابحث في الوجبات...', savePrice: 'حفظ السعر', savedSuccess: 'تم الحفظ!', statusAvailable: 'متوفر', statusUnavailable: 'غير متوفر', quickPriceHint: 'يمكنك تعديل أي سعر مباشرة وحفظه فورياً',
    editItemTitle: 'تعديل بيانات الطبق', addItemTitle: 'إضافة وجبة جديدة للقائمة', nameAr: 'اسم الوجبة بالعربية', nameEn: 'اسم الوجبة بالإنجليزية', descAr: 'الوصف بالعربية', descEn: 'الوصف بالإنجليزية', price: 'السعر', origPrice: 'السعر قبل الخصم (اختياري)', category: 'الصنف / الفئة', selectCategory: 'اختر الصنف', prepTime: 'وقت التحضير بالعربية', prepTimeEn: 'وقت التحضير بالإنجليزية', itemCalories: 'السعرات الحرارية', itemImage: 'صورة الطبق', imageUploadOrUrl: 'اختر صورة من جهازك لرفعها إلى Drive أو ضع رابطاً مباشراً', chooseFromDevice: 'اختر صورة من جهازك', orDirectUrl: 'أو رابط صورة مباشر (URL)', saveToDriveAuto: 'حفظ في Google Drive تلقائياً', isChefSpecial: 'طبق الشيف المميز (عرض بارز)', isPopular: 'الأكثر طلباً ومبيعاً', isAvailable: 'متوفر للطلب', saveItemBtn: 'حفظ الوجبة', cancelEdit: 'إلغاء التعديل',
    categoriesTitle: 'إدارة الأصناف والأقسام', categoriesSubtitle: 'إضافة صنف جديد، تعديل الأسماء، أو حذف الأصناف', addNewCategory: 'إضافة صنف جديد', categoryNameAr: 'اسم الصنف بالعربية', categoryNameEn: 'اسم الصنف بالإنجليزية', categoryIcon: 'الأيقونة', saveCategory: 'حفظ الصنف', categoryItemsCount: 'عدد الأطباق المرتبطة', confirmDeleteCategory: 'هل أنت متأكد من حذف هذا الصنف؟', cannotDeleteCategoryHasItems: 'لا يمكن حذف الصنف لوجود أطباق مرتبطة به. يرجى نقل أو حذف الأطباق أولاً.',
    heroSettingsTitle: 'تخصيص نصوص واجهة Hero', heroSettingsSubtitle: 'تحكم في العنوان الرئيسي، الشعار، الإحصائيات، والطبق المميز في الواجهة الترحيبية', welcomeBadgeAr: 'شارة الترحيب (عربي)', welcomeBadgeEn: 'شارة الترحيب (إنجليزي)', heroTitleLine1Ar: 'السطر الأول من العنوان (عربي)', heroTitleLine1En: 'السطر الأول من العنوان (إنجليزي)', heroHighlightAr: 'النص الذهبي البارز (عربي)', heroHighlightEn: 'النص الذهبي البارز (إنجليزي)', heroTaglineAr: 'الوصف الترحيبي (عربي)', heroTaglineEn: 'الوصف الترحيبي (إنجليزي)', statBadges: 'شارات الإحصائيات الثلاث', badgeVal: 'القيمة', badgeLabelAr: 'النص (عربي)', badgeLabelEn: 'النص (إنجليزي)', featuredDishSection: 'الطبق المميز المعروض في Hero', featuredDishTitleAr: 'اسم الطبق المعروض (عربي)', featuredDishTitleEn: 'اسم الطبق المعروض (إنجليزي)', featuredDishSubtitleAr: 'الوصف المختصر (عربي)', featuredDishSubtitleEn: 'الوصف المختصر (إنجليزي)', featuredDishPrice: 'السعر المعروض', featuredDishImage: 'رابط صورة الطبق المعروض', saveHeroSettings: 'حفظ تعديلات واجهة Hero',
    adminSecurityTitle: 'بيانات المدير والأمان', newAdminUsername: 'اسم مستخدم المدير الجديد', newAdminPassword: 'كلمة مرور المدير الجديدة', restaurantDetails: 'معلومات المطعم والتواصل', restNameAr: 'اسم المطعم (عربي)', restNameEn: 'اسم المطعم (إنجليزي)', phone: 'رقم الهاتف', whatsapp: 'رقم الواتساب', addressAr: 'العنوان (عربي)', addressEn: 'العنوان (إنجليزي)', workingHoursAr: 'أوقات العمل (عربي)', workingHoursEn: 'أوقات العمل (إنجليزي)', currencyAr: 'رمز العملة (عربي)', currencyEn: 'رمز العملة (إنجليزي)', saveAllSettings: 'حفظ إعدادات المطعم والمدير', confirmTitle: 'تأكيد الإجراء', confirm: 'تأكيد'
  },
  en: {
    portalTitle: 'Welcome to Sultan Gourmet', portalSubtitle: 'Choose your interface to continue', customerView: 'Customer Menu', customerViewDesc: 'Explore our royal culinary dishes, ingredients, and prices', exploreMenuBtn: 'Enter Menu', openInNewTab: 'Open in Separate Page', standaloneMenuHint: 'Dedicated standalone page with zero admin controls', directMenuLink: 'Direct Menu Link', copyLinkSuccess: 'Menu link copied!', viewMenuPage: 'View Menu Page', adminView: 'Admin Control Portal', adminViewDesc: 'Manage categories and meals, update live prices, and customize Hero texts', enterAdminBtn: 'Sign in as Admin', defaultLoginHint: 'Default login: Username: admin / Password: admin123',
    loginTitle: 'Admin Portal Login', usernameLabel: 'Admin Username', passwordLabel: 'Password', loginAction: 'Login to Portal', loginError: 'Invalid username or password', cancel: 'Cancel',
    backToPortal: 'Home / Switch View', adminBadge: 'Admin Portal', logout: 'Log Out', searchPlaceholder: 'Search dishes, grills, desserts...', special: 'Gourmet', availableNow: 'Available Now', exploreMenu: 'Explore Menu', manageMenu: 'Admin Portal & Pricing', chefSpecial: "Chef's Choice",
    menuTitle: 'Exquisite Gourmet Menu', menuSubtitle: 'Delicious dishes freshly prepared daily by master chefs', allCategories: 'All', sortBy: 'Sort By', sortSpecialFirst: 'Special First', sortPopular: 'Most Popular', sortPriceAsc: 'Price: Low to High', sortPriceDesc: 'Price: High to Low', noItemsFound: 'No dishes match your search criteria', viewAllDishes: 'View All Dishes', searchResultFor: 'Search results for:', clearSearch: 'Clear Search',
    layoutMode: 'Layout View', layoutGrid: 'Grid Cards', layoutHorizontal: 'Horizontal Wide', layoutCarousel: 'Horizontal Carousel', layoutGridShort: 'Grid', layoutHorizontalShort: 'Horizontal', layoutCarouselShort: 'Carousel', prevDish: 'Previous Dish', nextDish: 'Next Dish', minutes: 'min', calories: 'kcal', popularBadge: 'Most Popular', specialBadge: 'Special', notAvailable: 'Temporarily Unavailable', discount: 'OFF', editItem: 'Edit', deleteItem: 'Delete',
    adminDashboardTitle: 'Restaurant Admin Dashboard', adminDashboardSubtitle: 'Manage categories, meals, live prices, and customize Hero content', tabItems: 'Meals & Prices', tabCategories: 'Categories', tabHero: 'Hero Text Customizer', tabDrive: 'Google Drive', tabSettings: 'Restaurant & Security', addNewItem: 'Add New Meal', itemsList: 'Dishes & Live Price Editor', searchInItems: 'Search meals...', savePrice: 'Save Price', savedSuccess: 'Saved!', statusAvailable: 'Available', statusUnavailable: 'Unavailable', quickPriceHint: 'You can update any price directly and save immediately',
    editItemTitle: 'Edit Dish Details', addItemTitle: 'Add New Meal to Menu', nameAr: 'Meal Name (Arabic)', nameEn: 'Meal Name (English)', descAr: 'Description (Arabic)', descEn: 'Description (English)', price: 'Price', origPrice: 'Original Price (Before discount - optional)', category: 'Category', selectCategory: 'Select Category', prepTime: 'Prep Time (Arabic)', prepTimeEn: 'Prep Time (English)', itemCalories: 'Calories (kcal)', itemImage: 'Dish Image', imageUploadOrUrl: 'Choose an image from your device for Drive upload or paste a URL', chooseFromDevice: 'Choose from Device', orDirectUrl: 'Or direct Image URL', saveToDriveAuto: 'Auto save to Google Drive', isChefSpecial: "Chef's Special (Featured Display)", isPopular: 'Most Popular / Best Seller', isAvailable: 'Available to order', saveItemBtn: 'Save Dish', cancelEdit: 'Cancel Edit',
    categoriesTitle: 'Category & Section Management', categoriesSubtitle: 'Add new category, edit names in Arabic/English, or remove categories', addNewCategory: 'Add New Category', categoryNameAr: 'Category Name (Arabic)', categoryNameEn: 'Category Name (English)', categoryIcon: 'Icon', saveCategory: 'Save Category', categoryItemsCount: 'Linked Dishes Count', confirmDeleteCategory: 'Are you sure you want to delete this category?', cannotDeleteCategoryHasItems: 'Cannot delete category because it has linked dishes. Please reassign or delete them first.',
    heroSettingsTitle: 'Customize Hero Section Texts', heroSettingsSubtitle: 'Control main titles, tagline, stat badges, and featured dish in the welcome screen', welcomeBadgeAr: 'Welcome Badge (Arabic)', welcomeBadgeEn: 'Welcome Badge (English)', heroTitleLine1Ar: 'Title Line 1 (Arabic)', heroTitleLine1En: 'Title Line 1 (English)', heroHighlightAr: 'Golden Highlight Title (Arabic)', heroHighlightEn: 'Golden Highlight Title (English)', heroTaglineAr: 'Welcome Tagline (Arabic)', heroTaglineEn: 'Welcome Tagline (English)', statBadges: 'The Three Stat Badges', badgeVal: 'Value', badgeLabelAr: 'Label (Arabic)', badgeLabelEn: 'Label (English)', featuredDishSection: 'Featured Dish in Hero', featuredDishTitleAr: 'Featured Dish Title (Arabic)', featuredDishTitleEn: 'Featured Dish Title (English)', featuredDishSubtitleAr: 'Featured Dish Subtitle (Arabic)', featuredDishSubtitleEn: 'Featured Dish Subtitle (English)', featuredDishPrice: 'Featured Dish Price', featuredDishImage: 'Featured Dish Image URL', saveHeroSettings: 'Save Hero Customizations',
    adminSecurityTitle: 'Admin Credentials & Security', newAdminUsername: 'New Admin Username', newAdminPassword: 'New Admin Password', restaurantDetails: 'Restaurant Info & Contact', restNameAr: 'Restaurant Name (Arabic)', restNameEn: 'Restaurant Name (English)', phone: 'Phone Number', whatsapp: 'WhatsApp Number', addressAr: 'Address (Arabic)', addressEn: 'Address (English)', workingHoursAr: 'Working Hours (Arabic)', workingHoursEn: 'Working Hours (English)', currencyAr: 'Currency Symbol (Arabic)', currencyEn: 'Currency Symbol (English)', saveAllSettings: 'Save Settings & Credentials', confirmTitle: 'Confirm Action', confirm: 'Confirm'
  },
  ku: {
    portalTitle: 'بەخێربێن بۆ Happy Kids Zone', portalSubtitle: 'بۆ بەردەوامبوون زمان و ڕووکاری خۆت هەڵبژێرە', customerView: 'مێنیوی کڕیار', customerViewDesc: 'خواردنە خۆشەکان، سناک، شیرینی و خواردنەوەکان ببینە', exploreMenuBtn: 'چوونە ناو مێنیو', openInNewTab: 'کردنەوە لە پەڕەیەکی جیاواز', standaloneMenuHint: 'پەڕەیەکی تایبەت بە مێنیو، بەبێ کۆنترۆڵی بەڕێوەبەر', directMenuLink: 'بەستەری ڕاستەوخۆی مێنیو', copyLinkSuccess: 'بەستەری مێنیو کۆپی کرا!', viewMenuPage: 'بینینی مێنیو', adminView: 'پەنێڵی بەڕێوەبەر', adminViewDesc: 'بەڕێوەبردنی خواردن و نرخەکان و ڕێکخستنی ڕووکاری مێنیو', enterAdminBtn: 'چوونەژوورەوە وەک بەڕێوەبەر', defaultLoginHint: 'چوونەژوورەوەی بنەڕەتی: admin / admin123',
    loginTitle: 'چوونەژوورەوەی پەنێڵی بەڕێوەبەر', usernameLabel: 'ناوی بەکارهێنەر', passwordLabel: 'وشەی نهێنی', loginAction: 'چوونەژوورەوە', loginError: 'ناوی بەکارهێنەر یان وشەی نهێنی هەڵەیە', cancel: 'هەڵوەشاندنەوە',
    backToPortal: 'سەرەکی / گۆڕینی ڕووکەر', adminBadge: 'بەڕێوەبەر', logout: 'چوونەدەرەوە', searchPlaceholder: 'گەڕان بۆ خواردن، کباب، شیرینی...', special: 'تایبەت', availableNow: 'بەردەستە ئێستا', exploreMenu: 'بینینی مێنیو', manageMenu: 'پەنێڵی بەڕێوەبەر و نرخەکان', chefSpecial: 'هەڵبژاردەی چێف',
    menuTitle: 'مێنیوی خواردنە خۆشەکان', menuSubtitle: 'خواردنە تازەکان هەموو ڕۆژێک بە دەستی چێفە شارەزاکان ئامادە دەکرێن', allCategories: 'هەموو', sortBy: 'ڕیزکردن', sortSpecialFirst: 'تایبەتەکان یەکەم', sortPopular: 'زۆرترین داواکراو', sortPriceAsc: 'نرخ: لە کەم بۆ زۆر', sortPriceDesc: 'نرخ: لە زۆر بۆ کەم', noItemsFound: 'هیچ خواردنێک لەگەڵ گەڕانەکەت نەگونجا', viewAllDishes: 'هەموو خواردنەکان ببینە', searchResultFor: 'ئەنجامی گەڕان بۆ:', clearSearch: 'سڕینەوەی گەڕان',
    layoutMode: 'شێوازی پیشاندان', layoutGrid: 'پیشاندانی کارت', layoutHorizontal: 'پیشاندانی ئاسۆیی', layoutCarousel: 'شریتی ئاسۆیی', layoutGridShort: 'کارت', layoutHorizontalShort: 'ئاسۆیی', layoutCarouselShort: 'شریتی', prevDish: 'خواردنی پێشوو', nextDish: 'خواردنی داهاتوو', minutes: 'خولەک', calories: 'کالۆری', popularBadge: 'زۆرترین داواکراو', specialBadge: 'خواردنی تایبەت', notAvailable: 'کاتییە بەردەست نییە', discount: 'داشکاندن', editItem: 'دەستکاری', deleteItem: 'سڕینەوە',
    adminDashboardTitle: 'پەنێڵی بەڕێوەبردنی چێشتخانە', adminDashboardSubtitle: 'بەڕێوەبردنی خواردن، پۆلەکان، نرخەکان و ناوەڕۆکی مێنیو', tabItems: 'خواردن و نرخەکان', tabCategories: 'پۆلەکان', tabHero: 'دەستکاریکردنی ناوەڕۆک', tabDrive: 'Google Drive', tabSettings: 'زانیاری چێشتخانە و پاراستن', addNewItem: 'زیادکردنی خواردنی نوێ', itemsList: 'لیستی خواردن و دەستکاریکردنی نرخ', searchInItems: 'گەڕان لە خواردنەکان...', savePrice: 'پاشەکەوتکردنی نرخ', savedSuccess: 'پاشەکەوت کرا!', statusAvailable: 'بەردەستە', statusUnavailable: 'بەردەست نییە', quickPriceHint: 'دەتوانیت هەر نرخێک ڕاستەوخۆ دەستکاری و پاشەکەوت بکەیت',
    editItemTitle: 'دەستکاریکردنی زانیاری خواردن', addItemTitle: 'زیادکردنی خواردنی نوێ بۆ مێنیو', nameAr: 'ناوی خواردن بە عەرەبی', nameEn: 'ناوی خواردن بە ئینگلیزی', descAr: 'وەسف بە عەرەبی', descEn: 'وەسف بە ئینگلیزی', price: 'نرخ', origPrice: 'نرخی پێش داشکاندن (ئارەزوومەندانە)', category: 'پۆل', selectCategory: 'پۆلێک هەڵبژێرە', prepTime: 'کاتی ئامادەکردن بە عەرەبی', prepTimeEn: 'کاتی ئامادەکردن بە ئینگلیزی', itemCalories: 'کالۆری', itemImage: 'وێنەی خواردن', imageUploadOrUrl: 'وێنە هەڵبژێرە یان بەستەری وێنە دابنێ', chooseFromDevice: 'هەڵبژاردن لە ئامێر', orDirectUrl: 'یان بەستەری ڕاستەوخۆی وێنە', saveToDriveAuto: 'پاشەکەوتکردنی خۆکار لە Google Drive', isChefSpecial: 'خواردنی تایبەتی چێف', isPopular: 'زۆرترین داواکراو', isAvailable: 'بەردەستە بۆ داواکاری', saveItemBtn: 'پاشەکەوتکردنی خواردن', cancelEdit: 'هەڵوەشاندنەوەی دەستکاری',
    categoriesTitle: 'بەڕێوەبردنی پۆلەکان', categoriesSubtitle: 'زیادکردن، دەستکاریکردن یان سڕینەوەی پۆلەکان', addNewCategory: 'زیادکردنی پۆلی نوێ', categoryNameAr: 'ناوی پۆل بە عەرەبی', categoryNameEn: 'ناوی پۆل بە ئینگلیزی', categoryIcon: 'ئایکۆن', saveCategory: 'پاشەکەوتکردنی پۆل', categoryItemsCount: 'ژمارەی خواردنە پەیوەندیدارەکان', confirmDeleteCategory: 'دڵنیایت لە سڕینەوەی ئەم پۆلە؟', cannotDeleteCategoryHasItems: 'ئەم پۆلە ناتوانرێت بسڕدرێتەوە چونکە خواردنی پەیوەندیداری هەیە.',
    heroSettingsTitle: 'ڕێکخستنی دەقی Hero', heroSettingsSubtitle: 'دەستکاری سەردێر، دەقی بەخێرهاتن، ئامار و خواردنی تایبەت بکە', welcomeBadgeAr: 'نیشانی بەخێرهاتن (عەرەبی)', welcomeBadgeEn: 'نیشانی بەخێرهاتن (ئینگلیزی)', heroTitleLine1Ar: 'هێڵی یەکەمی سەردێر (عەرەبی)', heroTitleLine1En: 'هێڵی یەکەمی سەردێر (ئینگلیزی)', heroHighlightAr: 'دەقی جەختکراو (عەرەبی)', heroHighlightEn: 'دەقی جەختکراو (ئینگلیزی)', heroTaglineAr: 'دەقی بەخێرهاتن (عەرەبی)', heroTaglineEn: 'دەقی بەخێرهاتن (ئینگلیزی)', statBadges: 'سێ نیشانی ئامار', badgeVal: 'بەها', badgeLabelAr: 'دەق (عەرەبی)', badgeLabelEn: 'دەق (ئینگلیزی)', featuredDishSection: 'خواردنی تایبەت لە Hero', featuredDishTitleAr: 'ناوی خواردن (عەرەبی)', featuredDishTitleEn: 'ناوی خواردن (ئینگلیزی)', featuredDishSubtitleAr: 'وەسفی کورت (عەرەبی)', featuredDishSubtitleEn: 'وەسفی کورت (ئینگلیزی)', featuredDishPrice: 'نرخی خواردن', featuredDishImage: 'بەستەری وێنەی خواردن', saveHeroSettings: 'پاشەکەوتکردنی ڕێکخستنەکان',
    adminSecurityTitle: 'زانیاری بەڕێوەبەر و پاراستن', newAdminUsername: 'ناوی بەکارهێنەری نوێ', newAdminPassword: 'وشەی نهێنی نوێ', restaurantDetails: 'زانیاری چێشتخانە و پەیوەندی', restNameAr: 'ناوی چێشتخانە (عەرەبی)', restNameEn: 'ناوی چێشتخانە (ئینگلیزی)', phone: 'ژمارەی تەلەفۆن', whatsapp: 'ژمارەی واتساپ', addressAr: 'ناونیشان (عەرەبی)', addressEn: 'ناونیشان (ئینگلیزی)', workingHoursAr: 'کاتی کارکردن (عەرەبی)', workingHoursEn: 'کاتی کارکردن (ئینگلیزی)', currencyAr: 'نیشانی دراو (عەرەبی)', currencyEn: 'نیشانی دراو (ئینگلیزی)', saveAllSettings: 'پاشەکەوتکردنی ڕێکخستنەکان', confirmTitle: 'پشتڕاستکردنەوە', confirm: 'پشتڕاستکردنەوە'
  }
};
