import { translations } from './i18n';

const ku: Record<string, string> = {
  portalTitle: 'بەخێربێن بۆ Happy Kids Zone',
  portalSubtitle: 'بۆ بەردەوامبوون زمان و ڕووکاری خۆت هەڵبژێرە',
  customerView: 'مێنیوی کڕیار',
  customerViewDesc: 'خواردنە خۆشەکان، سناک، شیرینی و خواردنەوەکان ببینە',
  exploreMenuBtn: 'چوونە ناو مێنیو',
  openInNewTab: 'کردنەوە لە پەڕەیەکی جیاواز',
  standaloneMenuHint: 'پەڕەیەکی تایبەت بە مێنیو، بەبێ کۆنترۆڵی بەڕێوەبەر',
  directMenuLink: 'بەستەری ڕاستەوخۆی مێنیو',
  copyLinkSuccess: 'بەستەری مێنیو کۆپی کرا!',
  viewMenuPage: 'بینینی مێنیو',
  adminView: 'پەنێڵی بەڕێوەبەر',
  adminViewDesc: 'بەڕێوەبردنی خواردن و نرخەکان و ڕێکخستنی مێنیو',
  enterAdminBtn: 'چوونەژوورەوە وەک بەڕێوەبەر',
  defaultLoginHint: 'چوونەژوورەوەی بنەڕەتی: admin / admin123',
  loginTitle: 'چوونەژوورەوەی پەنێڵی بەڕێوەبەر',
  usernameLabel: 'ناوی بەکارهێنەر', passwordLabel: 'وشەی نهێنی',
  loginAction: 'چوونەژوورەوە', loginError: 'ناوی بەکارهێنەر یان وشەی نهێنی هەڵەیە', cancel: 'هەڵوەشاندنەوە',
  backToPortal: 'سەرەکی / گۆڕینی ڕووکەر', adminBadge: 'بەڕێوەبەر', logout: 'چوونەدەرەوە',
  searchPlaceholder: 'گەڕان بۆ خواردن، کباب، شیرینی...', special: 'تایبەت', availableNow: 'بەردەستە ئێستا',
  exploreMenu: 'بینینی مێنیو', manageMenu: 'پەنێڵی بەڕێوەبەر و نرخەکان', chefSpecial: 'هەڵبژاردەی چێف',
  menuTitle: 'مێنیوی خواردنە خۆشەکان', menuSubtitle: 'خواردنە تازەکان هەموو ڕۆژێک بە دەستی چێفە شارەزاکان ئامادە دەکرێن',
  allCategories: 'هەموو', sortBy: 'ڕیزکردن', sortSpecialFirst: 'تایبەتەکان یەکەم', sortPopular: 'زۆرترین داواکراو',
  sortPriceAsc: 'نرخ: لە کەم بۆ زۆر', sortPriceDesc: 'نرخ: لە زۆر بۆ کەم', noItemsFound: 'هیچ خواردنێک لەگەڵ گەڕانەکەت نەگونجا',
  viewAllDishes: 'هەموو خواردنەکان ببینە', searchResultFor: 'ئەنجامی گەڕان بۆ:', clearSearch: 'سڕینەوەی گەڕان',
  layoutMode: 'شێوازی پیشاندان', layoutGrid: 'پیشاندانی کارت', layoutHorizontal: 'پیشاندانی ئاسۆیی', layoutCarousel: 'شریتی ئاسۆیی',
  layoutGridShort: 'کارت', layoutHorizontalShort: 'ئاسۆیی', layoutCarouselShort: 'شریتی', prevDish: 'خواردنی پێشوو', nextDish: 'خواردنی داهاتوو',
  minutes: 'خولەک', calories: 'کالۆری', popularBadge: 'زۆرترین داواکراو', specialBadge: 'خواردنی تایبەت', notAvailable: 'کاتییە بەردەست نییە',
  discount: 'داشکاندن', editItem: 'دەستکاری', deleteItem: 'سڕینەوە',
  adminDashboardTitle: 'پەنێڵی بەڕێوەبردنی چێشتخانە', adminDashboardSubtitle: 'بەڕێوەبردنی خواردن، پۆلەکان، نرخەکان و ناوەڕۆکی مێنیو',
  tabItems: 'خواردن و نرخەکان', tabCategories: 'پۆلەکان', tabHero: 'دەستکاریکردنی ناوەڕۆک', tabDrive: 'Google Drive', tabSettings: 'زانیاری چێشتخانە و پاراستن',
  addNewItem: 'زیادکردنی خواردنی نوێ', itemsList: 'لیستی خواردن و دەستکاریکردنی نرخ', searchInItems: 'گەڕان لە خواردنەکان...', savePrice: 'پاشەکەوتکردنی نرخ', savedSuccess: 'پاشەکەوت کرا!',
  statusAvailable: 'بەردەستە', statusUnavailable: 'بەردەست نییە', quickPriceHint: 'دەتوانیت هەر نرخێک ڕاستەوخۆ دەستکاری و پاشەکەوت بکەیت',
  nameAr: 'ناوی خواردن بە عەرەبی', nameEn: 'ناوی خواردن بە ئینگلیزی', descAr: 'وەسف بە عەرەبی', descEn: 'وەسف بە ئینگلیزی',
  price: 'نرخ', category: 'پۆل', selectCategory: 'پۆلێک هەڵبژێرە', prepTime: 'کاتی ئامادەکردن', itemCalories: 'کالۆری', itemImage: 'وێنەی خواردن',
  saveItemBtn: 'پاشەکەوتکردنی خواردن', cancelEdit: 'هەڵوەشاندنەوەی دەستکاری',
  categoriesTitle: 'بەڕێوەبردنی پۆلەکان', categoriesSubtitle: 'زیادکردن، دەستکاریکردن یان سڕینەوەی پۆلەکان', addNewCategory: 'زیادکردنی پۆلی نوێ',
  categoryNameAr: 'ناوی پۆل بە عەرەبی', categoryNameEn: 'ناوی پۆل بە ئینگلیزی', categoryIcon: 'ئایکۆن', saveCategory: 'پاشەکەوتکردنی پۆل',
  categoryItemsCount: 'ژمارەی خواردنە پەیوەندیدارەکان', confirmDeleteCategory: 'دڵنیایت لە سڕینەوەی ئەم پۆلە؟',
  heroSettingsTitle: 'ڕێکخستنی دەقی Hero', heroSettingsSubtitle: 'دەستکاری سەردێر، دەقی بەخێرهاتن، ئامار و خواردنی تایبەت بکە',
  welcomeBadgeAr: 'نیشانی بەخێرهاتن (عەرەبی)', welcomeBadgeEn: 'نیشانی بەخێرهاتن (ئینگلیزی)',
  adminSecurityTitle: 'زانیاری بەڕێوەبەر و پاراستن', restaurantDetails: 'زانیاری چێشتخانە و پەیوەندی', phone: 'ژمارەی تەلەفۆن', whatsapp: 'ژمارەی واتساپ',
  confirmTitle: 'پشتڕاستکردنەوە', confirm: 'پشتڕاستکردنەوە'
};

// Keep every existing translation key available, then override it with Kurdish.
(translations as Record<string, Record<string, string>>).ku = {
  ...(translations.en || {}),
  ...ku,
};
